/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [NUMERO_DOCUMENTO]
      ,[CONSECUTIVO]
      ,[CODIGO_PRODUCTO]
      ,[UNIDAD_MEDIDA]
      ,[CODIGO_BODEGA]
      ,[LOTE]
      ,[NOMBRE]
      ,[FECHA_FABRICACION]
      ,[FECHA_VENCIMIENTO]
      ,[CANTIDAD]
      ,[HORA_REGISTRO]
      ,[FECHA_REGISTRO]
      ,[CODIGO_USUARIO]
      ,[OBSERVACION]
      ,[ID_ACTIVO]
      ,[TAG_INFO]
  FROM [UPL].[dbo].[T010_MOVIMIENTO_DET]

SELECT CODIGO_PRODUCTO, 
       UNIDAD_MEDIDA,
       LOTE,
	   SUM(SALDO_INICIAL) AS SALDO_INICIAL,
	   SUM(ENTRADAS) AS ENTRADAS,
	   SUM(SALIDAS) AS SALIDAS,
	   SUM(ENTRADAS - SALIDAS) AS TOTAL
FROM 
(
  SELECT D.CODIGO_PRODUCTO, 
         D.UNIDAD_MEDIDA,
         D.LOTE,
	     SUM(D.CANTIDAD) AS SALDO_INICIAL,
	     0 AS ENTRADAS,
	     0 AS SALIDAS
		 FROM  T010_MOVIMIENTO_DET D
		 INNER JOIN T009_MOVIMIENTO_ENC E ON E.NUMERO_DOCUMENTO = D.NUMERO_DOCUMENTO
		 WHERE SUBSTRING(E.CODIGO_DOCUMENTO_ADM, 1, 2) = 'SI'
         GROUP BY D.CODIGO_PRODUCTO, D.UNIDAD_MEDIDA, D.LOTE
  UNION ALL
  SELECT D.CODIGO_PRODUCTO, 
         D.UNIDAD_MEDIDA,
         D.LOTE,
		 0 AS SALDO_INICIAL,
	     SUM(D.CANTIDAD) AS ENTRADAS,
	     0 AS SALIDAS
		 FROM  T010_MOVIMIENTO_DET D
		 INNER JOIN T009_MOVIMIENTO_ENC E ON E.NUMERO_DOCUMENTO = D.NUMERO_DOCUMENTO
		 WHERE SUBSTRING(E.CODIGO_DOCUMENTO_ADM, 1, 2) = 'EN'
         GROUP BY D.CODIGO_PRODUCTO, D.UNIDAD_MEDIDA, D.LOTE
  UNION ALL
  SELECT D.CODIGO_PRODUCTO, 
         D.UNIDAD_MEDIDA,
         D.LOTE,
		 0 AS SALDO_INICIAL,
	     0 AS ENTRADAS,
	     SUM(D.CANTIDAD) AS SALIDAS
		 FROM  T010_MOVIMIENTO_DET D
		 INNER JOIN T009_MOVIMIENTO_ENC E ON E.NUMERO_DOCUMENTO = D.NUMERO_DOCUMENTO
		 WHERE SUBSTRING(E.CODIGO_DOCUMENTO_ADM, 1, 2) = 'SA'
         GROUP BY D.CODIGO_PRODUCTO, D.UNIDAD_MEDIDA, D.LOTE
) AS X
GROUP BY CODIGO_PRODUCTO, UNIDAD_MEDIDA, LOTE
ORDER BY CODIGO_PRODUCTO, UNIDAD_MEDIDA, LOTE