UPDATE T010_MOVIMIENTO_DET
SET  NOMBRE = LTRIM(RTRIM(D.CODIGO_PRODUCTO)) + ', ' + 
                LTRIM(RTRIM(P.NOMBRE)) + ', ' + 
				LTRIM(RTRIM(D.UNIDAD_MEDIDA)) + ', ' + 
				LTRIM(RTRIM(D.LOTE)) + ', ' + 
				LTRIM(RTRIM(B.NOMBRE)) 
FROM
    T010_MOVIMIENTO_DET D
INNER JOIN T008_PRODUCTO P ON D.CODIGO_PRODUCTO = P.CODIGO_PRODUCTO AND  D.UNIDAD_MEDIDA = P.UNIDAD_MEDIDA
INNER JOIN T005_BODEGA B ON D.CODIGO_BODEGA = B.CODIGO_BODEGA

UPDATE T012_MOVIMIENTO_DET_H
SET  NOMBRE = LTRIM(RTRIM(D.CODIGO_PRODUCTO)) + ', ' + 
                LTRIM(RTRIM(P.NOMBRE)) + ', ' + 
				LTRIM(RTRIM(D.UNIDAD_MEDIDA)) + ', ' + 
				LTRIM(RTRIM(D.LOTE)) + ', ' + 
				LTRIM(RTRIM(B.NOMBRE)) 
FROM
    T012_MOVIMIENTO_DET_H D
INNER JOIN T008_PRODUCTO P ON D.CODIGO_PRODUCTO = P.CODIGO_PRODUCTO AND  D.UNIDAD_MEDIDA = P.UNIDAD_MEDIDA
INNER JOIN T005_BODEGA B ON D.CODIGO_BODEGA = B.CODIGO_BODEGA